#ifndef COMP4985_GAME_PROTOTYPE_V0_STATE_H
#define COMP4985_GAME_PROTOTYPE_V0_STATE_H

enum game_state {
    INIT_STATE,
    MAIN_GAME_STATE,
    SCOREBOARD_STATE,
    EXIT_STATE
};

#endif //COMP4985_GAME_PROTOTYPE_V0_STATE_H
